### PR TITLE
switch to gradle as build tool

### PR DESCRIPTION
**Pull request by davidB**
Because it is simpler to manage:
* less verbose
* allow to have computed configuration (version from git describe, copyright year from current date,...)
* allow to select witch project to publish (without copy/paste)
* remove the need of the travis.sh
* quicker build
* easier to maintain (IMHO)

Now I need to setup credential to publish on bintray + link to jcenter + sync to maven central.

### CODE REVIEW

**Comment by bhs** [comment]
@davidB if you get the credentials to work with TravisCI or CircleCI (and gradle, I mean), please ping @bhs – I made an attempt to do that for something else a few months ago and failed. :)

Thanks.

**Comment by davidB** [comment]
@bhs ,Sorry I don't understand what you mean.

I included into .travis.yml the secured env variable to publish on my own bintray repository (for test). It worked. But to be able to publish on the opentracing bintray repository, I guess you should:
*  give to me (https://bintray.com/davidb) the permission to write in the bintray repo (https://bintray.com/opentracing), then I could publish and complete the setup to link to jcenter, and later the setup to publish to maven central (in the correct groupId)
* OR change the secured env variable in .travis.yml to include BINTRAY_USER and BINTRAY_KEY for the travis project https://travis-ci.org/search/opentracing-contrib%252Fjava-span-reporter

Thanks

**Comment by bhs** [comment]
@davidB I added you to the opentracing bintray group... hope that helps! Sorry for the delay, btw, feel free to ping me on Gitter if I'm blocking you.

**Comment by davidB** [comment]
Thanks.

**Pull request merged**
