### PR TITLE
upgrade support for io.opentracing:opentracing-api:0.33.0

### PR DESCRIPTION
**Pull request by IUSR**
1. `AutoFinishScopeManager` is deprecated in 0.32.0 then removed in 0.33.0; its functions looked the same as `ThreadLocalScopeManager`;
2. Cope with interface changes from tracer, span builder and span;
3. Support tags of generics types via `getKey()` when placed in the internal map with key type of `String`; this is also what Jaeger client is implemented.
4. Removed `SpanContextR` for which I don't see any usage.

### CODE REVIEW

**Comment by IUSR** [comment]
The changes look simple enough to me but since there's no unit tests, I don't know if there would be runtime bugs.

**Comment by IUSR** [comment]
Any comments? @davidB  @bhs

**Comment by kcirone** [comment]
Would love to see these changes merged, have made almost identical changes for OT 0.33.0 support for our solution but mgmt is not excited about managing our own version of a 3rd party lib...

**Comment by IUSR** [comment]
After 2 weeks of this PR, I asked our internal team to set up a Jenkins job for the clone and publish the artifacts to our internal Nexus, with the version deliberately bumped a lot greater to reserve the room in case it's merged here.

**Comment by davidB** [comment]
Sorry for delay (vacations, off-line, busy,...)

Thanks for the PR and the pings

**Comment by kcirone** [comment]
Thanks very much - Maven artifacts are updated as well?

Kevin C.

On 8/29/2019 3:32 AM, David Bernard wrote:
>
> Sorry for delay (vacations, off-line, busy,...)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_opentracing-2Dcontrib_java-2Dspan-2Dreporter_pull_12-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAGKZT7UNBKBDRI733OI7CFDQG53RVA5CNFSM4IHXBS32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5NRRTQ-23issuecomment-2D526063822&d=DwMCaQ&c=RoP1YumCXCgaWHvlZYR8PZh8Bv7qIrMUB65eapI_JnE&r=kuEIhRPjVgRDtsjURVnhY936xUHGS6C8TAI111C5w7E&m=yn_yw1Jpe1av86fVYSAFlLQB7i3ybd7P5mSXzdo-aRU&s=r4KnPbZjYDBscOw0e5RhDX9IWqBprAroUUzpmPE4Xmg&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGKZT7Q2PFTH4UY5MTLSD5TQG53RVANCNFSM4IHXBS3Q&d=DwMCaQ&c=RoP1YumCXCgaWHvlZYR8PZh8Bv7qIrMUB65eapI_JnE&r=kuEIhRPjVgRDtsjURVnhY936xUHGS6C8TAI111C5w7E&m=yn_yw1Jpe1av86fVYSAFlLQB7i3ybd7P5mSXzdo-aRU&s=CvaJtlLP2ctfTmnUIj4KhRG9S5BramKTh4DyTYtop3Y&e=>.
>
-- 
Thanks, Kevin

Oracle <http://www.oracle.com>
Kevin Cirone | Consulting Member of Technical Staff
Phone: +17817440139 <tel:+17817440139>
95 Network Drive | Burlington, MA 01803
Green Oracle <http://www.oracle.com/commitment> Oracle is committed to 
developing practices and products that help protect the environment

**Comment by davidB** [comment]
yes the artifact is available on jcenter see https://bintray.com/opentracing/maven/span-reporter
version 0.2.0 includes this PR

**Comment by kcirone** [comment]
I don't see 0.2.0 up there, only 0.1.0

On 8/29/2019 11:54 AM, David Bernard wrote:
>
> yes the artifact is available on jcenter see 
> https://bintray.com/opentracing/maven/span-reporter 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__bintray.com_opentracing_maven_span-2Dreporter&d=DwMCaQ&c=RoP1YumCXCgaWHvlZYR8PZh8Bv7qIrMUB65eapI_JnE&r=kuEIhRPjVgRDtsjURVnhY936xUHGS6C8TAI111C5w7E&m=kwb857-Zk-qyeOto1tXNl0XPMUn6Tgto4dR-wJ_OB60&s=ymurQ8UKdtq00WR-lMueqsnFJ0d6SxXrqO-rmOAHeGA&e=>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_opentracing-2Dcontrib_java-2Dspan-2Dreporter_pull_12-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAGKZT7UOH55LIB4IAACRJ33QG7WLPA5CNFSM4IHXBS32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5O65JQ-23issuecomment-2D526249638&d=DwMCaQ&c=RoP1YumCXCgaWHvlZYR8PZh8Bv7qIrMUB65eapI_JnE&r=kuEIhRPjVgRDtsjURVnhY936xUHGS6C8TAI111C5w7E&m=kwb857-Zk-qyeOto1tXNl0XPMUn6Tgto4dR-wJ_OB60&s=kqXq5Y1La9wI75zd6OXFjwr6goB7PML1P3oSO4qFBtE&e=>, 
> or mute the thread 
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AGKZT7WOE2XCDWGFTFJKY53QG7WLPANCNFSM4IHXBS3Q&d=DwMCaQ&c=RoP1YumCXCgaWHvlZYR8PZh8Bv7qIrMUB65eapI_JnE&r=kuEIhRPjVgRDtsjURVnhY936xUHGS6C8TAI111C5w7E&m=kwb857-Zk-qyeOto1tXNl0XPMUn6Tgto4dR-wJ_OB60&s=BdF3sXlqd6mYvwFTi8U-r0l7RRLh6a61v8lbnm3Cs04&e=>.
>
-- 
Thanks, Kevin

Oracle <http://www.oracle.com>
Kevin Cirone | Consulting Member of Technical Staff
Phone: +17817440139 <tel:+17817440139>
95 Network Drive | Burlington, MA 01803
Green Oracle <http://www.oracle.com/commitment> Oracle is committed to 
developing practices and products that help protect the environment

**Comment by davidB** [comment]
should be fixed now or in a couple of minutes

**Comment by IUSR** [comment]
Thanks! I can see the new version on bintray.

**Pull request merged**
